export const GET_APP_DATA = 'GET_APP_DATA';

export const FIGURE_NAME = 'FIGURE_NAME';

export const GET_DESTINY_DESCRIPTION = 'GET_DESTINY_DESCRIPTION';
export const GET_BIRTH_DESCRIPTION = 'GET_BIRTH_DESCRIPTION';
export const GET_HEART_DESCRIPTION = 'GET_HEART_DESCRIPTION';
export const GET_PERSONALITY_DESCRIPTION = 'GET_PERSONALITY_DESCRIPTION';
export const GET_REALITY_DESCRIPTION = 'GET_REALITY_DESCRIPTION';

export const GET_ESSENCE_DESCRIPTION = 'GET_ESSENCE_DESCRIPTION';
export const GET_PERSONAL_DESCRIPTION = 'GET_PERSONAL_DESCRIPTION';
export const GET_UNIVERSAL_DESCRIPTION = 'GET_UNIVERSAL_DESCRIPTION';
export const GET_PINNACLE_DESCRIPTION = 'GET_PINNACLE_DESCRIPTION';
export const GET_CHALLENGE_DISCRIPTION = 'GET_CHALLENGE_DISCRIPTION';
